CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  cat TEXT NOT NULL,
  name TEXT NOT NULL,
  sku TEXT NOT NULL,
  price REAL NOT NULL,
  oldPrice REAL,
  price2 REAL,
  price3 REAL,
  unit TEXT NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  vat TEXT NOT NULL DEFAULT 'vat',
  image TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS folders (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS files (
  id TEXT PRIMARY KEY,
  folder_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  name TEXT NOT NULL,
  size_label TEXT NOT NULL,
  r2_key TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  department TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL,
  address TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS users (
  username TEXT PRIMARY KEY,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer'
);
