name = "thananan-pricelist-api"
main = "src/index.js"
compatibility_date = "2025-01-01"
account_id = "16bf0a91e5640e6b32c52eea359c7783"

[[d1_databases]]
binding = "DB"
database_name = "thananan-pricelist-db"
database_id = "e15155b4-42b3-4539-9f1a-495a6862f788"

[[r2_buckets]]
binding = "FILES"
bucket_name = "thananan-pricelist-files"
